config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'users#index'

  resources :users, only: [:index, :show] do
    collection do
      get :search
    end
  end

  resources :professions do
    collection do
      get :search
    end
  end

  resources :tasks do
    collection do
      get :created
      get :assigned
    end
    member do
      patch :update_status
    end
    resource :rating, only: [:new, :create]
  end

  resources :discussions do
    resources :comments
  end

  get 'leaderboard/index' => 'leaderboard#index'
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  #=====ASSOCIATIONS====================================================================================================
  belongs_to :user
  has_many :comments, dependent: :destroy

  #=====VALIDATIONS=====================================================================================================
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: %i[ show edit update destroy ]
  before_action :authorize_discussion, only: [:edit, :update, :destroy]

  def index
    @discussions = Discussion.includes(:user).all.order(updated_at: :desc)
  end

  def show
    @comments = @discussion.comments.includes(:user).order(updated_at: :asc)
    @comment = Comment.new
  end

  def new
    @discussion = Discussion.new
  end

  def edit
  end

  def create
    @discussion = current_user.discussions.build(discussion_params)
    if @discussion.save
      redirect_to discussion_url(@discussion), notice: "Discussion was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @discussion.update(discussion_params)
      redirect_to discussion_url(@discussion), notice: "Discussion was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @discussion.destroy
    redirect_to discussions_url, notice: "Discussion was successfully destroyed."
  end

  private
  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

  def discussion_params
    params.require(:discussion).permit(:title, :body, :user_id)
  end

  def authorize_discussion
    authorize @discussion
  end
end

app/views/discussions/_form.html.erb
<%= form_with(model: discussion) do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>
      <ul>
        <% discussion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="discussion-form">
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, rows: 5, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h3>Editing Discussion</h3>
<%= render "form", discussion: @discussion %>
<br>

<div class="back-link">
  <%= link_to "<i class='fas fa-arrow-left'></i> Back to discussion".html_safe, discussion_path, class: 'btn btn-secondary' %>
</div>

app/views/discussions/index.html.erb
<%= link_to 'Start a New Discussion', new_discussion_path, class: 'btn btn-primary new-discussion-btn' %>

<ul class="discussion-list">
  <% @discussions.each do |discussion| %>
    <li class="discussion-item">
      <div class="discussion-row">
        <h3 class="discussion-title">
          <%= link_to discussion.title, discussion_path(discussion), class: 'discussion-link' %>
        </h3>
        <span>
          <i class="discussion-meta fas fa-comments"></i> <%= discussion.comments_count %> comments
        </span>
      </div>
      <p class="discussion-body"><%= truncate(discussion.body, length: 100) %></p>
      <p class="discussion-meta">
        <i class="fas fa-user"></i> Posted by: <%= discussion.user.full_name %> &nbsp; &nbsp;
        <% if discussion.updated_at.present? && discussion.updated_at > discussion.created_at %>
          <i class="fas fa-clock"></i> Updated <%= time_ago_in_words(discussion.updated_at) %> ago
        <% else %>
          <i class="fas fa-clock"></i> Created <%= time_ago_in_words(discussion.created_at) %> ago
        <% end %>
      </p>
    </li>
  <% end %>
</ul>

app/views/discussions/new.html.erb
<h3>New discussion</h3>
<%= render "form", discussion: @discussion %>
<br>

<div class="back-link">
  <%= link_to "<i class='fas fa-arrow-left'></i> Back to discussions".html_safe, discussions_path, class: 'btn btn-secondary' %>
</div>

app/views/discussions/show.html.erb
<div class="discussion">
  <div class="discussion-row">
    <h3> <%= @discussion.title %></h3>
    <span>
      <div class="discussion-actions">
        <% if policy(@discussion).update? %>
          <%= link_to edit_discussion_path(@discussion), class: 'btn btn-secondary btn-sm' do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>

        <% if policy(@discussion).destroy? %>
          <%= link_to discussion_path(@discussion), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </span>
  </div>

  <p class="discussion-body"><%= @discussion.body %></p>
  <p class="discussion-meta">
    <i class="fas fa-user"></i> Posted by: <%= @discussion.user.full_name %> &nbsp; &nbsp;
    <% if @discussion.updated_at.present? && @discussion.updated_at > @discussion.created_at %>
      <i class="fas fa-clock"></i> Updated <%= time_ago_in_words(@discussion.updated_at) %> ago
    <% else %>
      <i class="fas fa-clock"></i> Created <%= time_ago_in_words(@discussion.created_at) %> ago
    <% end %>
  </p>
</div>

<br>

<% if @comments.present? %>
  <h5>Comments Posted</h5>

  <% @comments.each do |comment| %>
    <div class="comment">
      <div class="discussion-row">
        <p class="comment-body"><%= comment.body %></p>
        <span>
          <div class="comment-actions">
            <% if policy(comment).update? %>
              <%= link_to edit_discussion_comment_path(@discussion, comment), class: 'btn btn-secondary btn-sm' do %>
                <i class="fas fa-edit"></i>
              <% end %>
            <% end %>

            <% if policy(comment).destroy? %>
              <%= link_to discussion_comment_path(@discussion, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
                <i class="fas fa-trash-alt"></i>
            <% end %>
            <% end %>
          </div>
        </span>
      </div>
      <p class="discussion-meta">
        <i class="fas fa-user"></i> Posted by: <%= comment.user.full_name %> &nbsp; &nbsp;
        <% if comment.updated_at.present? && comment.updated_at > comment.created_at %>
          <i class="fas fa-clock"></i> Updated <%= time_ago_in_words(comment.updated_at) %> ago
        <% else %>
          <i class="fas fa-clock"></i> Created <%= time_ago_in_words(comment.created_at) %> ago
        <% end %>
      </p>
    </div>
  <% end %>
<% end %>
<br>
<h5><i class="fas fa-pencil-alt"></i> Post a New Comment</h5>

<%= form_with(model: [@discussion, @comment], local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@comment.errors.count, "error") %> prevented this comment from being posted:</h4>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_area :body, rows: 3, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Post Comment', class: 'btn btn-primary' %>
  </div>
<% end %>

<div class="back-link">
  <%= link_to "<i class='fas fa-arrow-left'></i> Back to discussions".html_safe, discussions_path, class: 'btn btn-secondary' %>
</div>