config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'users#index'

  resources :users, only: [:index, :show] do
    collection do
      get :search
    end
  end

  resources :professions do
    collection do
      get :search
    end
  end

  resources :tasks do
    collection do
      get :created
      get :assigned
    end
    member do
      patch :update_status
    end
    resource :rating, only: [:new, :create]
  end

  resources :discussions do
    resources :comments
  end

  get 'leaderboard/index' => 'leaderboard#index'
end

app/models/task.rb
class Task < ApplicationRecord
  #=====ASSOCIATIONS====================================================================================================
  belongs_to :creator, class_name: 'User', foreign_key: 'created_by_user_id'
  belongs_to :assignee, class_name: 'User', foreign_key: 'assigned_to_user_id'
  has_one :rating, dependent: :destroy

  #=====ENUMS===========================================================================================================
  enum status: { created: 0, viewed: 1, accepted: 2, in_progress: 3, completed: 4, cancelled: 5 }
  enum priority: { low: 0, medium: 1, high: 2 }

  #=====VALIDATIONS=====================================================================================================
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true
  validates :status, inclusion: { in: statuses.keys }
  validates :priority, presence: true
  validates :due_date, presence: true
  validate :assignee_is_not_creator
  validate :status_transition_is_valid

  #=====FILTERS=========================================================================================================
  def self.ransackable_attributes(auth_object = nil)
    %w[created_by_user_id assigned_to_user_id created_at due_date priority status]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[creator assignee]
  end

  #=====CALLBACKS=======================================================================================================
  before_create :set_default_status
  before_save :set_completion_date, if: :status_changed_to_completed?

  #=====SCOPES==========================================================================================================
  scope :tasks_completed, ->(user) { where(assigned_to_user_id: user.id, status: 'completed').count }

  private
  def assignee_is_not_creator
    if assignee == creator
      errors.add(:assignee, "can't be the same as the creator")
    end
  end

  def set_default_status
    self.status ||= :created
  end

  def status_transition_is_valid
    if status_changed? && status_was.present?
      valid_transitions = {
        "created" => ["viewed"],
        "viewed" => ["accepted", "cancelled"],
        "accepted" => ["in_progress"],
        "in_progress" => ["completed"],
        "completed" => [],
        "cancelled" => []
      }

      unless valid_transitions[status_was].include?(status)
        errors.add(:status, "cannot transition from #{status_was.humanize} to #{status.humanize}")
      end
    end
  end

  def status_changed_to_completed?
    status_changed? && status == 'completed'
  end

  def set_completion_date
    self.completion_date = Time.current
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  include Pagy::Backend

  before_action :set_task, only: %i[show edit update destroy update_status]

  def created
    @q = Task.where(created_by_user_id: current_user.id).ransack(params[:q])
    @pagy, @created_tasks = pagy(@q.result(distinct: true).includes(:assignee).order(created_at: :desc))
    @search_url = created_tasks_path
  end

  def assigned
    @q = Task.where(assigned_to_user_id: current_user.id).ransack(params[:q])
    @pagy, @assigned_tasks = pagy(@q.result(distinct: true).includes(:creator).order(created_at: :desc))
    @search_url = assigned_tasks_path
  end

  def new
    @task = Task.new
    if params[:user_id].present?
      if params[:user_id].to_i == current_user.id
        flash[:alert] = "You cannot create a task for yourself."
        redirect_to users_path and return
      else
        # If the user_id is valid and not the current user, assign it to @assignee
        @assignee = User.find(params[:user_id])
      end
    else
      flash[:alert] = "No user selected for the task."
      redirect_to users_path
    end
  end

  def create
    @task = current_user.created_tasks.build(task_params)
    if @task.save
      redirect_to task_path(@task), notice: 'Task was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    if @task.assigned_to_user_id == current_user.id && @task.status == 'created'
      @task.update(status: 'viewed')
    end
  end

  def edit
    @task = Task.find(params[:id])
    if @task.completed?
      redirect_to task_path(@task), flash: { alert: 'You cannot edit a completed task.' }
    else
      @assignee = @task.assigned_to_user_id.present? ? User.find(@task.assigned_to_user_id) : nil
    end
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task), notice: 'Task was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: 'Task was successfully deleted.'
  end

  def update_status
    authorize @task, :update_status?

    if @task.update(status: params[:task][:status])
      flash[:notice] = "Task status updated successfully."
    else
      flash[:alert] = "Failed to update task status."
    end

    redirect_to task_path(@task)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :assigned_to_user_id, :status, :priority, :due_date, :comments)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title, class: "required-field"  %>
    <%= form.text_field :title, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: "required-field"  %>
    <%= form.text_area :description, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :priority, class: "required-field"  %>
    <%= form.select :priority, Task.priorities.keys.map { |priority| [priority.humanize, priority] }, {}, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :due_date, class: "required-field" %><br />
    <div class="field">
      <%= form.datetime_local_field :due_date, value: @task.due_date&.strftime('%Y-%m-%dT%H:%M'), min: (Time.current + 1.day).strftime('%Y-%m-%dT%H:%M'), class: 'form-control', required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :comments %>
    <%= form.text_area :comments, class: 'form-control' %>
  </div>

  <%= form.hidden_field :assigned_to_user_id, value: @assignee.id %>

  <div class="nav-actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
    <% if @task.persisted? %>
      <%= link_to 'Back to Task', task_path(@task), class: 'btn btn-secondary' %>
    <% end %>
  </div>
<% end %>

app/views/tasks/assigned.html.erb
<%= render 'layouts/search_form' %>

<div class="users-list">
  <% @assigned_tasks.each do |task| %>
    <%= link_to task_path(task), class: "user-card-link" do %>
      <div class="user-card">
        <h3><%= task.title %></h3>
        <p class="user-detail" title="Status"><i class="fas fa-clipboard-list"></i> <%= task.status.humanize %></p>
        <p class="user-detail" title="Priority"><i class="fas fa-flag"></i> <%= task.priority.humanize %></p>
        <p class="user-detail" title="Due Date"><i class="fas fa-calendar-check"></i> <%= format_datetime(task.due_date) %></p>
        <p class="user-detail" title="Created By"><i class="fas fa-user"></i> <%= task.creator.full_name %></p>
      </div>
    <% end %>
  <% end %>
</div>

<div class="pagination-container">
  <%== pagy_bootstrap_nav(@pagy).html_safe if @pagy.pages > 1 %>
</div>
<div class="pagination-info">
  <%== pagy_info(@pagy) %>
</div>

app/views/tasks/created.html.erb
<%= render 'layouts/search_form' %>

<div class="users-list">
  <% @created_tasks.each do |task| %>
    <%= link_to task_path(task), class: "user-card-link" do %>
      <div class="user-card">
        <h5 class="user-name"><%= task.title %></h5>
        <p class="user-detail" title="Status"><i class="fas fa-clipboard-list"></i> <%= task.status.humanize %></p>
        <p class="user-detail" title="Priority"><i class="fas fa-flag"></i> <%= task.priority.humanize %></p>
        <p class="user-detail" title="Due Date"><i class="fas fa-calendar-check"></i> <%= format_datetime(task.due_date) %></p>
        <p class="user-detail" title="Assigned To"><i class="fas fa-user-tag"></i> <%= task.assignee.full_name %></p>
      </div>
    <% end %>
  <% end %>
</div>

<div class="pagination-container">
  <%== pagy_bootstrap_nav(@pagy).html_safe if @pagy.pages > 1 %>
</div>
<div class="pagination-info">
  <%== pagy_info(@pagy) %>
</div>

app/views/tasks/edit.html.erb
<h4>Edit Task</h4>
<%= render 'form', task: @task %>

app/views/tasks/new.html.erb
<h4>New Task</h4>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="user-details">
  <h4> <%= @task.title %></h4>

  <div class="detail-item">
    <i class="fas fa-info-circle"></i> <strong>Description:</strong> <span><%= @task.description %></span>
  </div>

  <div class="detail-item">
    <i class="fas fa-clipboard-list"></i> <strong>Status:</strong> <span class="status-<%= @task.status %>"><%= @task.status.humanize %></span>
  </div>

  <div class="detail-item">
    <i class="fas fa-user"></i> <strong>Created by:</strong> <span><%= link_to @task.creator.full_name, user_path(@task.creator), class: 'user-link' %></span>
  </div>

  <div class="detail-item">
    <i class="fas fa-user-tag"></i> <strong>Assigned to:</strong> <span><%= link_to @task.assignee.full_name, user_path(@task.assignee), class: 'user-link' %></span>
  </div>

  <div class="detail-item">
    <i class="fas fa-calendar-alt"></i> <strong>Created at:</strong> <span><%= format_datetime(@task.created_at) %></span>
  </div>

  <div class="detail-item">
    <i class="fas fa-flag"></i> <strong>Priority:</strong> <span><%= @task.priority %></span>
  </div>

  <div class="detail-item">
    <i class="fas fa-calendar-check"></i> <strong>Due date:</strong> <span><%= format_datetime(@task.due_date) %></span>
  </div>

  <% if @task.status == 'completed' %>
    <div class="detail-item">
      <i class="fas fa-check-circle"></i> <strong>Completed at:</strong> <span><%= format_datetime(@task.completion_date) %></span>
    </div>

    <% if @task.rating.present? %>
      <div class="detail-item">
        <i class="fas fa-star"></i> <strong>Rating:</strong> <span><% @task.rating.rating.times { %> <i class="fas fa-star"></i><% } %><%= @task.rating.rating %>/5</span>

        <% if @task.rating.comment.present? %>
          <div class="detail-item">
            <i class="fas fa-comment"></i> <strong>Comment:</strong> <span><%= @task.rating.comment %></span>
          </div>
        <% end %>
      </div>
    <% else %>
      <%= link_to 'Rate Task', new_task_rating_path(@task), class: 'btn btn-success' %>
    <% end %>
  <% end %>

  <div class="task-actions">
    <% if policy(@task).update_status? %>
      <% if policy(@task).permitted_statuses.include?('accepted') && @task.status == 'viewed' %>
        <%= button_to 'Accept', update_status_task_path(@task, task: { status: 'accepted' }), method: :patch, class: 'btn task-btn btn-outline-success' %>
      <% end %>

      <% if policy(@task).permitted_statuses.include?('cancelled') && @task.status == 'viewed' %>
        <%= button_to 'Cancel', update_status_task_path(@task, task: { status: 'cancelled' }), method: :patch, class: 'btn task-btn btn-outline-dark' %>
      <% end %>

      <% if policy(@task).permitted_statuses.include?('in_progress') && @task.status == 'accepted' %>
        <%= button_to 'Start Task', update_status_task_path(@task, task: { status: 'in_progress' }), method: :patch, class: 'btn task-btn btn-outline-success' %>
      <% end %>

      <% if policy(@task).permitted_statuses.include?('completed') && @task.status == 'in_progress' %>
        <%= button_to 'Complete', update_status_task_path(@task, task: { status: 'completed' }), method: :patch, class: 'btn task-btn btn-outline-dark' %>
      <% end %>
    <% end %>
  </div>

  <div class="nav-actions">
    <% if !@task.completed? %>
      <%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-primary' %>
    <% end %>
    <% path = @task.creator == current_user ? created_tasks_path : assigned_tasks_path %>
    <%= link_to 'Back to Tasks', path, class: 'btn btn-secondary' %>
    <%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </div>
</div>