config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'users#index'

  resources :users, only: [:index, :show] do
    collection do
      get :search
    end
  end

  resources :professions do
    collection do
      get :search
    end
  end

  resources :tasks do
    collection do
      get :created
      get :assigned
    end
    member do
      patch :update_status
    end
    resource :rating, only: [:new, :create]
  end

  resources :discussions do
    resources :comments
  end

  get 'leaderboard/index' => 'leaderboard#index'
end

app/views/layouts/_search_form.html.erb
<div class="search-form-container">
  <%= search_form_for @q, url: @search_url, method: :get do |f| %>
    <div class="row">
      <% if cname? == 'users' %>
        <div class="col-md-2">
          <%= f.label :id_in, "Name", class: "form-label" %>
          <%= f.collection_select :id_in, User.all, :id, :full_name, {}, { multiple: true, id: "user-full-name", class: "select2 form-control form-control-sm" } %>
        </div>

        <div class="col-md-2">
          <%= f.label :professions_id_in, "Profession", class: "form-label" %>
          <%= f.collection_select :professions_id_in, Profession.all, :id, :name, {}, { multiple: true, id: "profession-select", class: "select2 form-control form-control-sm" } %>
        </div>

        <div class="col-md-2">
          <%= f.label :experience_years_gteq, "Experience", class: "form-label" %>
          <%= f.number_field :experience_years_gteq, class: "form-control form-control-sm" %>
        </div>

        <div class="col-md-2">
          <%= f.label :pin_code_eq, "Pin Code", class: "form-label" %>
          <%= f.text_field :pin_code_eq, class: "form-control form-control-sm" %>
        </div>

        <div class="col-md-2">
          <%= f.label :district_eq, "District", class: "form-label" %>
          <%= f.text_field :district_eq, class: "form-control form-control-sm" %>
        </div>

      <% elsif cname? == 'tasks'%>
        <% if aname? == 'assigned'%>
          <div class="col-md-2">
            <%= f.label :created_by_user_id_in, 'Created By' %>
            <%= f.collection_select :created_by_user_id_in, User.all, :id, :full_name,
                                    { prompt: 'Select User' },
                                    { multiple: true, id: "user-full-name", class: "form-control form-control-sm" } %>
          </div>
        <% end %>

        <% if aname? == 'created' %>
          <div class="col-md-2">
            <%= f.label :assigned_to_user_id_in, 'Assigned To' %>
            <%= f.collection_select :assigned_to_user_id_in, User.all, :id, :full_name,
                         { prompt: 'Select User' },
                         { multiple: true, id: "user-full-name", class: "form-control form-control-sm" } %>
          </div>
        <% end %>

        <div class="col-md-2">
          <%= f.label :status_eq, "Status" %>
          <%= f.select :status_eq, Task.statuses.keys.map { |status| [status.titleize, Task.statuses[status]] }, { include_blank: 'All' }, class: 'form-control form-control-sm' %>
        </div>

        <div class="col-md-2">
          <%= f.label :priority_eq, "Priority" %>
          <%= f.select :priority_eq, Task.priorities.keys.map { |priority| [priority.titleize, Task.priorities[priority]] }, { include_blank: 'All' }, class: 'form-control form-control-sm' %>
        </div>

        <div class="col-md-2">
          <%= f.label :created_at_gteq, "Created From" %>
          <%= f.date_field :created_at_gteq, class: 'form-control form-control-sm' %>
        </div>

        <div class="col-md-2">
          <%= f.label :created_at_lteq, "Created To" %>
          <%= f.date_field :created_at_lteq, class: 'form-control form-control-sm' %>
        </div>

        <div class="col-md-2">
          <%= f.label :due_date_gteq, "Due From" %>
          <%= f.date_field :due_date_gteq, class: 'form-control form-control-sm' %>
        </div>

        <div class="col-md-2">
          <%= f.label :due_date_lteq, "Due To" %>
          <%= f.date_field :due_date_lteq, class: 'form-control form-control-sm' %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col">
        <%= f.submit "Filter", class: "btn btn-primary btn-sm mt-3" %>
        <%= link_to 'Clear Filters', @search_url, class: "btn btn-secondary btn-sm mt-3 ml-2" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_sidebar_links.html.erb
<div class="side-link">
  <li><%= link_to 'Available Users', users_path, class: 'side-link-item' %></li>
  <li><%= link_to 'Tasks Created', created_tasks_path, class: 'side-link-item' %></li>
  <li><%= link_to 'Tasks Assigned', assigned_tasks_path, class: 'side-link-item' %></li>
  <li><%= link_to 'Discussions', discussions_path, class: 'side-link-item' %></li>
  <li><%= link_to 'Leader Board', leaderboard_index_path, class: 'side-link-item' %></li>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManPower</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>

  <body>
  <div class="alert-container">
    <% if notice.present? %>
      <div class="alert alert-success">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-danger">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <%= alert %>
      </div>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <div class="top-bar">
      <div class="user-info">
        <span>Welcome, <%= current_user.full_name %>!</span>
        <%= link_to 'Edit Account', edit_user_registration_path, class: 'button' %>
        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' %>
      </div>
      <div class="app-info">
        <span>Total Users: <%= User.total_users %></span>
      </div>
    </div>

    <div class="container-area">
      <div class="sidebar-left">
        <ul class="nav">
          <%= render 'layouts/sidebar_links' %>
        </ul>
      </div>

      <div class="content-center">
        <%= yield %>
      </div>
    </div>
  <% else %>
    <div class="auth-container">
      <%= yield %>
    </div>
  <% end %>
  </body>
</html>